[project]
name = "smartpy"
version = "0.0.2"
authors = [
    { name = "Othmane Zoheir", email = "othmane@rumorz.io" },
]
description = "Python utility knife"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    'pandas',
    'numpy',
    'psutil'
]

[project.urls]
Homepage = "https://github.com/zozoheir/smartpy"
Issues = "https://github.com/zozoheir/smartpy/issues"
