package:
  name: smartpy
  version: 1.0.0

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

about:
  home: https://github.com/zozoheir/smartpy
  license: MIT
  summary: General stuff
