name: Run tests and create a tag on success

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create a new tag on success
        if: success()
        run: |
          git config --local user.email "zozoheir@umich.edu"
          git config --local user.name "zozoheir"
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0")
          new_tag="v$((${latest_tag//[^0-9]/} + 1))"
          git tag $new_tag
          git push origin $new_tag
